"""empty message

Revision ID: a093feb5ed1d
Revises: 
Create Date: 2023-09-25 10:20:45.684710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a093feb5ed1d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cool_user")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cool_user",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "username", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column(
            "password_hash", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "registered_on", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("admin", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "public_id", sa.VARCHAR(length=36), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="cool_user_pkey"),
        sa.UniqueConstraint("email", name="cool_user_email_key"),
        sa.UniqueConstraint("public_id", name="cool_user_public_id_key"),
        sa.UniqueConstraint("username", name="cool_user_username_key"),
    )
    # ### end Alembic commands ###
